### ISSUE TITLE
City dialog issues

### ISSUE THREAD

**Issue by ilehtoranta** [rajko-horvat/OpenCiv1#60] opened 2024-07-20 20:58 UTC
**Describe the bug**
The city dialog gets very very slow if the worked city tile is removed

**To Reproduce**
1. Start a new game
2. Build first city
3. Go to city dialog and remove the worked city tile
4. The game gets very very slow.
5. After a while it is possible to exit city dialog but the game keeps running slow

![Capture](https://github.com/user-attachments/assets/b035f9f4-7586-47bb-9ab9-ccd1a34e5c3f)

Compiled from the latest commit as a release build:
2ae8d81 - Finish CityWorker code block translation, adjust namespaces, add city Improvement and wonder names where possible

My educated guess is that it is related to this. This is my first attempt with OpenCiv so I don't have experience from older builds except Alpha7.

**Comment by rajko-horvat** [comment] 2024-07-21 15:24
Yes, you are completely right.
Thank you for catching this.

The code is currently unstable, so I'm unable to commit all changes, but you can manually change the following code (in CityWorker.cs) to fix the issue:
```c#
private void F0_1d12_6dfe(short cityID, int size)
{
	this.oCPU.Log.EnterBlock($"F0_1d12_6dfe({cityID}, {size})");

	// function body
	while (this.Var_6542 > 0 && this.oParent.Var_70e4 < this.Var_6542)
	{
		this.Var_6542--;
		this.oParent.Var_70e4++;
	}

	// Instruction address 0x1d12:0x6e16, size: 5
	this.oParent.Var_70e2 = this.oParent.Segment_2dc4.F0_2dc4_007c_CheckValueRange(this.oParent.Var_70e2, 0, this.oParent.CivState.Cities[cityID].ActualSize);
	// Instruction address 0x1d12:0x6e98, size: 5
	this.oParent.Var_70e4 = this.oParent.Segment_2dc4.F0_2dc4_007c_CheckValueRange(this.oParent.Var_70e4, 0, this.oParent.CivState.Cities[cityID].ActualSize);

	// Instruction address 0x1d12:0x6ebb, size: 5
	while ((this.oParent.Var_70e2 + this.oParent.Var_70e4) > this.oParent.Segment_2dc4.F0_2dc4_007c_CheckValueRange(this.oParent.CivState.Cities[cityID].ActualSize - size, 0, 99))
	{
		if (this.Var_6542 > 0)
		{
			this.Var_6542--;
		}
		else
		{
			this.oParent.Var_70e2--;

			// Instruction address 0x1d12:0x6e74, size: 5
			this.oParent.Var_70e2 = this.oParent.Segment_2dc4.F0_2dc4_007c_CheckValueRange(this.oParent.Var_70e2, 0, this.oParent.CivState.Cities[cityID].ActualSize);
		}

		this.oParent.Var_70e4--;

		// Instruction address 0x1d12:0x6e98, size: 5
		this.oParent.Var_70e4 = this.oParent.Segment_2dc4.F0_2dc4_007c_CheckValueRange(this.oParent.Var_70e4, 0, this.oParent.CivState.Cities[cityID].ActualSize);
	}

	// Far return
	this.oCPU.Log.ExitBlock("F0_1d12_6dfe");
}
```

**Comment by ilehtoranta** [comment] 2024-07-21 21:44
Thanks, this fixed it. Unfortunately, it freezed later with similar symptoms during enemy turn.

**Comment by rajko-horvat** [comment] 2024-07-22 05:46
> Thanks, this fixed it. Unfortunately, it froze later with similar symptoms during the enemy turn.

Sorry to hear that. I guess that there is some other loop which makes problems and locks. I'm slowly introducing int (32 bit) variables as I go. Before they were all short (16bit), even if there was an error there would be faster overflow from 65535 to 0 than from 4M to 0...

Can you provide a save game which produces said problem. Even if it's already freezing it doesn't matter. Just try to save game data.

> Turns out that if a barbarian captures a city game can crash. Could not retrieve log.txt this time, though.

I disabled the log.txt automatic generation because of a performance issues (it was often a very large file). You can enable log generation by changing  enableLog = true in (CivGame.cs). I will introduce Exception.log file in the next commit which will record possible exception every time.

**Comment by ilehtoranta** [comment] 2024-07-22 21:35
Unfortunately I have no save game. It didn't save the game and didn't progress far enough to trigger autosave.

I enabled logging in my build and will see if I can get something... should occur again soonish.

**Comment by ilehtoranta** [comment] 2024-07-24 22:45
Here is another crash that I got today. I didn't save game, so this is all I have.

				F0_1d12_6dfe(12, 0)
				{
				}
				F0_1d12_6c97_PlayerHasWonder(0, 2)
				{
				}
				F0_1d12_6c97_PlayerHasWonder(0, 21)
				{
				}
				F0_1d12_6cf3_GetWonderCityID(11)
				{
				}
				F0_1d12_6c97_PlayerHasWonder(0, 13)
				{
				}
				F0_1d12_6dfe(12, 0)
				{
				}
				
				Exception message: Index was outside the bounds of the array.
				Exception source: OpenCiv1
				Exception stack trace:    at OpenCiv1.CityWorker.F0_1d12_0045_ProcessCityState(Int16 cityID, Int16 flag)
   at OpenCiv1.Segment_1ade.F0_1ade_0006(Int16 playerID)
   at OpenCiv1.Segment_1238.F0_1238_0092()
   at OpenCiv1.Segment_11a8.F0_11a8_0008_Main()
   at OpenCiv1.CivGame.Start()
   at OpenCiv1.UI.MainWindow.GameThread()

**Comment by rajko-horvat** [comment] 2024-07-25 08:13
> Here is another crash that I got today. I didn't save game, so this is all I have.

You may want to compile as Debug and not Release when debugging code, because all I see is what happened, and the function in which the error happened, but I can't see at what exact location (line) in the code the exception happened.

**Comment by rajko-horvat** [comment] 2024-08-01 20:02
I'm going to close this because the original issue was confirmed as fixed.

**Closed by rajko-horvat** 2024-08-01 20:02 UTC
