### ISSUE TITLE
Civilopedia missing summaries

### ISSUE THREAD

**Issue by richardpenman** [rajko-horvat/OpenCiv1#23] opened 2023-12-31 03:37 UTC
![Screenshot_2023-12-30_19-28-32](https://github.com/rajko-horvat/OpenCiv1/assets/26063146/7035495d-d153-4495-92be-83ad2ac42826)

**Comment by rajko-horvat** [comment] 2023-12-31 14:32
I could not reproduce the bug (using the latest commit):
![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/1aab345d-c6ae-4861-b6b6-5e08027f8ba2)
![image](https://github.com/rajko-horvat/OpenCiv1/assets/121714236/23fcc60d-1caa-4790-b137-c3385fc9de69)

Closed as not a bug anymore.

**Closed by rajko-horvat** 2023-12-31 14:32 UTC

**Comment by richardpenman** [comment] 2023-12-31 19:49
Confirmed this is fixed in the latest commit. You are amazingly productive!

**Comment by rajko-horvat** [comment] 2024-01-02 00:03
> Confirmed this is fixed in the latest commit. You are amazingly productive!

Thanks ;)
